services:
  waddontv:
    build: .
    image: waddontv
    container_name: waddontv
    ports:
      - "8781:8781"
    restart: unless-stopped
    env_file:
      - .env

# Profil dev : build local depuis les sources
# Usage: docker compose --profile dev up -d --build
  waddontv-dev:
    build: .
    image: waddontv-dev
    container_name: waddontv-dev
    ports:
      - "8781:8781"
    restart: unless-stopped
    env_file:
      - .env
    profiles:
      - dev